#!/usr/bin/env php

<?php

use Illuminate\Container\Container;
use Illuminate\Filesystem\Filesystem;
use Surgiie\Blade\Blade;

require __DIR__.'/vendor/autoload.php';

$container = new Container;

$blade = new Blade($container, new Filesystem);

$contents = $blade->compile($argv[1], [
    'message' => 'wtf',
    'dogs' => ['rex', 'charlie', 'steve'],
    'name' => 'Bob',
    'favoriteFood' => 'Pizza',
    'oldest' => 1,
    'serverName' => 'example.com',
    'mainEndpoint' => 'example',
    'accessLogPath' => '/var/log/nginx.access_log',
    'apiEndpoint' => [
        '/api/v1/foo',
        '/api/v1/bar',
        '/api/v1/baz',
    ],
]);

file_put_contents(dirname($argv[1]).'/test.rendered', $contents);
